# Generated by Django 5.0.6 on 2024-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
